# Generated by Django 4.2.2 on 2023-09-26 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0002_remove_advocate_age_advocate_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LawFirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('estd_date', models.DateField(default='2000-01-01')),
                ('is_suspend', models.BooleanField(default=False)),
                ('email', models.EmailField(default='default@gmail.com', max_length=254)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_lawfirms', to='userapp.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='LawfirmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
        ),
        migrations.CreateModel(
            name='LawfirmAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(default='2000-01-01')),
                ('phone', models.CharField(max_length=200)),
                ('address', models.CharField(default='not given', max_length=200)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('is_owner', models.BooleanField(default=False)),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AdvocateLawfirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_status', models.BooleanField(default=True)),
                ('invitation_status', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_owner', models.BooleanField(default=False)),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.advocate')),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
        ),
    ]
