# Generated by Django 4.1.4 on 2023-09-22 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirm', '0002_alter_lawfirm_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocatelawfirm',
            name='invitation_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawfirm',
            name='email',
            field=models.EmailField(default='default@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='advocatelawfirm',
            name='advocate_status',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='LawfirmNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('created_at', models.DateField(auto_now=True)),
                ('lawfirm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lawfirm.lawfirm')),
            ],
        ),
    ]
