# Generated by Django 4.2.2 on 2023-09-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lawfirm', '0003_advocatelawfirm_invitation_status_lawfirm_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocatelawfirm',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='advocatelawfirm',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
