# Generated by Django 4.1.4 on 2023-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0002_associationmembershippayment_payment_association_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='instamojo_API_KEY',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='association',
            name='instamojo_AUTH_TOKEN',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='association',
            name='is_suspend',
            field=models.BooleanField(default=False, max_length=200),
        ),
    ]
