# Generated by Django 4.2.2 on 2023-09-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0004_advocateassociation_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationpaymentrequest',
            name='payment_expiry_date',
            field=models.DateTimeField(default='2000-01-01'),
        ),
    ]
