# Generated by Django 4.2.2 on 2023-09-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0005_alter_associationpaymentrequest_payment_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationpaymentrequest',
            name='payment_expiry_date',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
