# Generated by Django 4.2.2 on 2023-09-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0006_alter_associationpaymentrequest_payment_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmembershippayment',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
    ]
