# Generated by Django 4.2.2 on 2023-09-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0007_associationmembershippayment_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationmembershippayment',
            name='have_fine',
            field=models.CharField(default='No fines', max_length=20),
        ),
    ]
