# Generated by Django 4.2.2 on 2023-09-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0008_associationmembershippayment_have_fine'),
    ]

    operations = [
        migrations.AddField(
            model_name='associationpaymentrequest',
            name='have_fine',
            field=models.CharField(default='No fines', max_length=20),
        ),
    ]
