# Generated by Django 4.2.2 on 2023-09-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0009_associationpaymentrequest_have_fine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associationmembershippayment',
            name='have_fine',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='associationpaymentrequest',
            name='have_fine',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
