# Generated by Django 4.2.2 on 2023-09-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('association', '0010_alter_associationmembershippayment_have_fine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=250)),
                ('place_of_pratice', models.CharField(max_length=250)),
            ],
        ),
    ]
