# Generated by Django 4.2.2 on 2023-09-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_remove_advocate_age_advocate_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advocate',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='phone',
            field=models.CharField(default='not given', max_length=200),
        ),
        migrations.AlterField(
            model_name='advocate',
            name='specialization',
            field=models.CharField(default='not given', max_length=200),
        ),
    ]
