# Generated by Django 4.1.4 on 2023-09-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_advocate_age_advocate_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
