# Generated by Django 4.2.2 on 2023-09-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_remove_advocate_age_advocate_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='advocate',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
