# Generated by Django 4.1.4 on 2023-09-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_userdata_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='otp',
            field=models.IntegerField(default='725892'),
        ),
    ]
